
version: '3.8'
services:
  lbx-proxy:
    build: ./images/lbx-proxy
    container_name: lbx-proxy
    volumes:
      - ./images/lbx-proxy/config/domains.json:/config/domains.json
      - ./volumes/certbot:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      lbx-network:
    environment:
      CERTBOT_ENVIRONMENT: "${CERTBOT_ENVIRONMENT}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
    restart: unless-stopped
    
  www-bubenbox:
    build: ./images/www1
    container_name: www-bubenbox
    networks:
      lbx-network:
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  lbx-network:
    driver: bridge
